[hooks]
pre-commit = [
    "cargo fmt --all -- --check",
    "cargo check",
    "cargo clippy --all-targets --all-features -- -D warnings",
]
pre-push = "cargo test"
post-commit = "echo yay! All tests passed. Don't forget to push your changes!"
[logging]
verbose = true
