name: Code Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:

      - name: Install ALSA development files
        run: sudo apt-get update && sudo apt-get install -y libasound2-dev
      - name: Install pkg-config
        run: sudo apt-get install -y pkg-config

      - name: Build and test
        run: cargo test --workspace --all-targets
      
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install grcov
        run: cargo install grcov

      - name: Generate code coverage
        env:
          CARGO_INCREMENTAL: "0"
          RUSTFLAGS: "-Cinstrument-coverage"
          RUSTDOCFLAGS: "-Cinstrument-coverage"
          LLVM_PROFILE_FILE: "coverage-%p-%m.profraw"
        run: |
          cargo test --workspace --all-targets
          grcov . \
            --binary-path ./target/debug/ \
            -s . \
            -t cobertura \
            --branch \
            --ignore-not-existing \
            --ignore "/*" \
            -o coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: stacksjb/Shell_Command_Menu
          files: coverage.xml
          fail_ci_if_error: true
